name: mailjet
channels:
  - defaults
dependencies:
  # Python/plugins
  - conda-forge::mypy
  - python=3.11
  - pytest
  - pytest-cov
  - pylint
  - pip
  # Python libraries
  - mypy
  - types-requests
  - requests>=2.4.3
  # Other
  - pre-commit
